# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CEFRLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Mastery')], max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_vocabulary', models.PositiveIntegerField(default=0)),
                ('max_vocabulary', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cefr_levels', to='languages.language')),
            ],
            options={
                'verbose_name': 'Уровень CEFR',
                'verbose_name_plural': 'Уровни CEFR',
                'db_table': 'cefr_levels',
                'ordering': ['order'],
                'unique_together': {('language', 'level')},
            },
        ),
    ]
