# Generated by Django 6.0.6 on 2026-06-27 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='Иконка')),
                ('category', models.CharField(choices=[('levels', 'По уровням CEFR'), ('reading', 'По чтению историй'), ('vocabulary', 'По словарному запасу'), ('reviews', 'По повторениям (SM-2)'), ('streaks', 'По стрикам'), ('duels', 'По дуэлям'), ('rating', 'По рейтингу'), ('grammar', 'По грамматике'), ('languages', 'По языкам'), ('ai', 'По AI тренеру'), ('rare', 'Редкие / секретные')], max_length=30, verbose_name='Категория')),
                ('condition', models.JSONField(blank=True, default=dict, verbose_name='Условие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон достижения',
                'verbose_name_plural': 'Шаблоны достижений',
                'db_table': 'achievements',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Полученное достижение',
                'verbose_name_plural': 'Полученные достижения',
                'db_table': 'user_achievements',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
