# Generated by Django 6.0.6 on 2026-06-25 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentence', models.TextField()),
                ('translation', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_from_story', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
                'db_table': 'grammar_examples',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('tip', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('ai_generated', 'Сгенерирован AI')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Урок грамматики',
                'verbose_name_plural': 'Уроки грамматики',
                'db_table': 'grammar_lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Выбор ответа'), ('fill_blank', 'Заполни пропуск'), ('true_false', 'Правда / Ложь'), ('translate', 'Переведи')], max_length=20)),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'db_table': 'grammar_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserGrammarProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён')], default='not_started', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('max_score', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Прогресс по грамматике',
                'verbose_name_plural': 'Прогресс по грамматике',
                'db_table': 'user_grammar_progress',
            },
        ),
    ]
