# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_player_one', models.PositiveSmallIntegerField(default=0)),
                ('score_player_two', models.PositiveSmallIntegerField(default=0)),
                ('rating_change_player_one', models.IntegerField(default=0)),
                ('rating_change_player_two', models.IntegerField(default=0)),
                ('avg_time_player_one', models.FloatField(blank=True, null=True)),
                ('avg_time_player_two', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Результат дуэли',
                'verbose_name_plural': 'Результаты дуэлей',
                'db_table': 'duel_results',
            },
        ),
        migrations.CreateModel(
            name='DuelRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer_player_one', models.CharField(blank=True, max_length=255)),
                ('answer_player_two', models.CharField(blank=True, max_length=255)),
                ('time_player_one', models.FloatField(blank=True, null=True)),
                ('time_player_two', models.FloatField(blank=True, null=True)),
                ('is_draw', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Раунд дуэли',
                'verbose_name_plural': 'Раунды дуэлей',
                'db_table': 'duel_rounds',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('casual', 'Casual'), ('rated', 'Рейтинговая')], default='casual', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание противника'), ('in_progress', 'В процессе'), ('finished', 'Завершена'), ('cancelled', 'Отменена'), ('draw', 'Ничья')], default='waiting', max_length=20)),
                ('round_type', models.CharField(choices=[('translate_word', 'Переведи слово'), ('choose_form', 'Выбери форму глагола'), ('build_sentence', 'Собери предложение'), ('fill_blank', 'Заполни пропуск')], default='translate_word', max_length=20)),
                ('total_rounds', models.PositiveSmallIntegerField(default=5)),
                ('current_round', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duels', to='languages.language')),
            ],
            options={
                'verbose_name': 'Дуэль',
                'verbose_name_plural': 'Дуэли',
                'db_table': 'duels',
                'ordering': ['-created_at'],
            },
        ),
    ]
