# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duels', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_as_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duel',
            name='player_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels_as_player_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_duels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duelresult',
            name='duel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='duels.duel'),
        ),
        migrations.AddField(
            model_name='duelround',
            name='duel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='duels.duel'),
        ),
        migrations.AddField(
            model_name='duelround',
            name='round_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_rounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duelround',
            name='story_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duel_rounds', to='stories.storyword'),
        ),
        migrations.AlterUniqueTogether(
            name='duelround',
            unique_together={('duel', 'round_number')},
        ),
    ]
