# Generated by Django 6.0.6 on 2026-06-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0002_initial'),
        ('languages', '0002_language_story_submission_min_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='round_type',
        ),
        migrations.AddField(
            model_name='duel',
            name='cefr_level',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.PROTECT, related_name='duels', to='languages.cefrlevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duel',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_type',
            field=models.CharField(choices=[('user', 'Игрок'), ('ai', 'AI тренер')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='duel',
            name='time_per_round_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='duelround',
            name='round_type',
            field=models.CharField(choices=[('translate_word', 'Переведи слово'), ('choose_form', 'Выбери форму глагола'), ('build_sentence', 'Собери предложение'), ('fill_blank', 'Заполни пропуск')], default='translate_word', max_length=20),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание противника'), ('in_progress', 'В процессе'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='duelround',
            name='answer_player_one',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='duelround',
            name='answer_player_two',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
