# Generated by Django 6.0.6 on 2026-06-25 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('daily_review', 'Ежедневное повторение слов'), ('streak_warning', 'Предупреждение о потере серии'), ('inactivity', 'Долго не заходил'), ('new_content', 'Новый контент на твоём уровне'), ('subscription_expiring', 'Подписка истекает через 3 дня')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки'), ('skipped', 'Пропущено')], default='pending', max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'db_table': 'reminders',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Каждый день'), ('every_2_days', 'Каждые 2 дня'), ('weekly', 'Каждую неделю'), ('smart', 'Умный — по активности')], default='daily', max_length=20)),
                ('preferred_time', models.TimeField(default='09:00')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Расписание напоминаний',
                'verbose_name_plural': 'Расписания напоминаний',
                'db_table': 'reminder_schedules',
            },
        ),
    ]
