# Generated by Django 6.0.6 on 2026-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('push', 'Push-уведомление')], default='telegram', max_length=15, verbose_name='Канал доставки'),
        ),
    ]
