# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_before', models.PositiveIntegerField()),
                ('score_after', models.PositiveIntegerField()),
                ('change', models.IntegerField()),
                ('reason', models.CharField(choices=[('duel_win', 'Победа в дуэли'), ('duel_loss', 'Поражение в дуэли'), ('duel_draw', 'Ничья'), ('season_reset', 'Сброс сезона'), ('manual', 'Ручная корректировка')], default='duel_win', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История рейтинга',
                'verbose_name_plural': 'История рейтингов',
                'db_table': 'rating_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=1000)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('total_duels', models.PositiveIntegerField(default=0)),
                ('win_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_ratings', to='languages.language')),
            ],
            options={
                'verbose_name': 'Рейтинг игрока',
                'verbose_name_plural': 'Рейтинги игроков',
                'db_table': 'player_ratings',
                'ordering': ['-score'],
            },
        ),
    ]
