# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duels', '0002_initial'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='duel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_changes', to='duels.duel'),
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='player_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ratings.playerrating'),
        ),
        migrations.AlterUniqueTogether(
            name='playerrating',
            unique_together={('user', 'language')},
        ),
    ]
