# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=255)),
                ('context_sentence', models.TextField(blank=True)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Существительное'), ('verb', 'Глагол'), ('adjective', 'Прилагательное'), ('adverb', 'Наречие'), ('pronoun', 'Местоимение'), ('preposition', 'Предлог'), ('conjunction', 'Союз'), ('other', 'Другое')], default='other', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('audio_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Слово истории',
                'verbose_name_plural': 'Слова историй',
                'db_table': 'story_words',
            },
        ),
        migrations.CreateModel(
            name='UserStoryProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('read_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Прогресс по истории',
                'verbose_name_plural': 'Прогресс по историям',
                'db_table': 'user_story_progress',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('ai_generated', 'Сгенерирована AI'), ('imported', 'Импортирована')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cefr_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='languages.cefrlevel')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
