# Generated by Django 6.0.6 on 2026-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='source',
            field=models.CharField(choices=[('manual', 'Вручную'), ('ai_generated', 'Сгенерирована AI'), ('ai_assisted', 'С помощью AI')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_review', 'На модерации'), ('published', 'Опубликована'), ('rejected', 'Отклонена'), ('archived', 'Архив')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='storyword',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storyword',
            name='context_sentence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storyword',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
