# Generated by Django 6.0.6 on 2026-06-27 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentevent',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='full_analytics',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='method',
            field=models.CharField(choices=[('card', 'Карта'), ('bank_account', 'Банковский счёт')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_story_assist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='global_leaderboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('semi_annual', 'Semi-annual'), ('annual', 'Annual')], default='free', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='stories_per_week',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider_payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат'), ('pending', 'В обработке'), ('manual', 'Ручная оплата')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plan',
            name='phrases_per_day',
            field=models.PositiveIntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stories_per_day',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.CreateModel(
            name='TrialPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='subscriptions.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_period', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пробный период',
                'verbose_name_plural': 'Пробные периоды',
                'db_table': 'trial_periods',
            },
        ),
    ]
