# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grammar', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=1)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_result', models.CharField(blank=True, choices=[('again', 'Снова — не помню'), ('hard', 'Сложно'), ('good', 'Хорошо'), ('easy', 'Легко')], max_length=10, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сессия повторения',
                'verbose_name_plural': 'Сессии повторений',
                'db_table': 'review_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserPhrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=150)),
                ('translation', models.CharField(max_length=255)),
                ('context_sentence', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('story', 'Из истории'), ('manual', 'Добавлено вручную'), ('grammar', 'Из урока грамматики'), ('duel', 'Из дуэли')], default='manual', max_length=20)),
                ('is_mastered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grammar_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_phrases', to='grammar.grammarlesson')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_phrases', to='languages.language')),
            ],
            options={
                'verbose_name': 'Фраза пользователя',
                'verbose_name_plural': 'Фразы пользователей',
                'db_table': 'user_phrases',
                'ordering': ['-created_at'],
            },
        ),
    ]
