# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userphrase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='learning.userphrase'),
        ),
        migrations.AlterUniqueTogether(
            name='userphrase',
            unique_together={('user', 'word', 'language')},
        ),
    ]
