# Generated by Django 6.0.6 on 2026-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphrase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Слово пользователя', 'verbose_name_plural': 'Слова пользователей'},
        ),
        migrations.RemoveField(
            model_name='userphrase',
            name='is_mastered',
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='consecutive_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userphrase',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userphrase',
            name='status',
            field=models.CharField(choices=[('active', 'Активное'), ('mastered', 'Выучено')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='reviewsession',
            name='last_result',
            field=models.CharField(blank=True, choices=[('again', 'Снова'), ('hard', 'Сложно'), ('good', 'Хорошо'), ('easy', 'Легко')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userphrase',
            name='context_sentence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userphrase',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
