# Generated by Django 6.0.6 on 2026-06-25 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('generate_story', 'Генерация истории'), ('explain_word', 'Объяснение слова'), ('explain_grammar', 'Объяснение грамматики'), ('generate_question', 'Генерация вопроса'), ('translate', 'Перевод')], max_length=30)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('cached', 'Из кэша')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI запрос',
                'verbose_name_plural': 'AI запросы',
                'db_table': 'ai_request_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
