# Generated by Django 6.0.6 on 2026-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='request_type',
            field=models.CharField(choices=[('generate_story', 'Генерация истории'), ('assist_story_creation', 'Помощь при создании истории'), ('explain_word', 'Объяснение слова'), ('explain_grammar', 'Объяснение грамматики'), ('generate_duel_question', 'Генерация вопроса для дуэли'), ('ai_duel_answer', 'Ответ AI тренера в дуэли')], max_length=30),
        ),
    ]
