# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('duel_invite', 'Вызов на дуэль'), ('duel_finished', 'Дуэль завершена'), ('duel_cancelled', 'Дуэль отменена'), ('rating_changed', 'Изменение рейтинга'), ('achievement', 'Достижение'), ('subscription_expired', 'Подписка истекла'), ('subscription_expiring', 'Подписка скоро истечёт'), ('new_story', 'Новая история'), ('system', 'Системное')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='duels.duel')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
