# Generated by Django 6.0.6 on 2026-06-25 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='stories.story'),
        ),
    ]
