# Generated by Django 6.0.6 on 2026-06-27 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('notifications', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='achievements.achievement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('websocket', 'WebSocket'), ('telegram', 'Telegram'), ('push', 'Push-уведомление')], default='websocket', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('duel_invite', 'Вызов на дуэль'), ('duel_finished', 'Дуэль завершена'), ('duel_cancelled', 'Дуэль отменена'), ('rating_changed', 'Изменение рейтинга'), ('achievement', 'Достижение'), ('friend_request', 'Запрос в друзья'), ('friend_accepted', 'Запрос в друзья принят'), ('subscription_expired', 'Подписка истекла'), ('subscription_expiring', 'Подписка скоро истечёт'), ('trial_expiring', 'Пробный период истекает'), ('new_story', 'Новая история'), ('review_ready', 'Слова к повторению'), ('system', 'Системное')], max_length=30),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField(max_length=500)),
                ('p256dh_key', models.CharField(blank=True, default='', max_length=255)),
                ('auth_key', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push-подписка',
                'verbose_name_plural': 'Push-подписки',
                'db_table': 'push_subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
